#!/bin/bash

# Helper functions

# not used yet
chromium-checked-mode () {
  open /usr/local/opt/dart/Chromium.app --args --checked
}

pub-clean () {
  rm -rf .pub .packages pubspec.lock && find . -name packages | xargs rm -rf
}

pub-clean-cache () {
  rm -rf ~/.pub-cache
}

# not used yet
pub-generate-tests () {
  pub run dart_dev gen-test-runner
}

pub-get () {
  pub get --packages-dir
}

pub-serve () {
  pub run dart_dev serve
}

# not used yet
pub-serve-chrome () {
  pub run dart_dev serve --web-compiler=dart2js
}

pub-upgrade () {
  pub upgrade
}

# not used yet
pub-get-solver () {
  pub get --packages-dir --verbosity=solver
}

# not used yet
pub-get-solver-inconsistent () {
  pub get --packages-dir --verbosity solver | grep "inconsistent" -A 2 | sed -e "s/\ |//g"
}

# qdart flag functions

q-clean () {
  echo '--- Cleaning root pub dependencies ---'
  pub-clean

  if [ -d "app" ]; then
    echo '--- Cleaning app pub dependencies ---'
    (cd app && pub-clean)
  fi

  if [ -d "test/signals" ]; then
    echo '--- Cleaning signals pub dependencies ---'
    (cd test/signals && pub-clean)
  fi
}

q-clean-hard () {
  echo '--- Cleaning root pub dependencies ---'
  pub-clean

  if [ -d "app" ]; then
    echo '--- Cleaning app pub dependencies ---'
    (cd app && pub-clean)
  fi

  if [ -d "test/signals" ]; then
    echo '--- Cleaning signals pub dependencies ---'
    (cd test/signals && pub-clean)
  fi

  echo '--- Clearing pub cache ---'
  pub-clean-cache
}

q-format () {
  echo '--- Formatting project ---'
  pub run dart_dev format
}

q-get () {
  echo '--- Getting root pub dependencies ---'
  pub-get

  if [ -d "app" ]; then
    echo '--- Getting app pub dependencies ---'
    (cd app && pub-get)
  fi

  if [ -d "test/signals" ]; then
    echo '--- Getting signals pub dependencies ---'
    (cd test/signals && pub-get)
  fi
}

q-serve () {
  if [ -d "app" ]; then
    echo '--- Serving project in app directory ---'
    (cd app && pub-serve)
  else
    echo '--- Serving project ---'
    pub-serve
  fi
}

q-test () {
  echo '--- Testing project ---'
  pub run dart_dev test
}

q-upgrade () {
  echo '--- Upgrading root pub dependencies ---'
  pub-upgrade

  if [ -d "app" ]; then
    echo '--- Upgrading app pub dependencies ---'
    (cd app && pub-upgrade)
  fi

  if [ -d "test/signals" ]; then
    echo '--- Upgrading signals pub dependencies ---'
    (cd test/signals && pub-upgrade)
  fi
}

usage () {
  echo "${underline}${bold}GNU Usage${normal}"
  echo "    ./qdart [options]"
  echo
  echo "${underline}${bold}POSIX Usage${normal}"
  echo "    ./qdart -[single letter options]"
  echo
  echo "${underline}${bold}Options${normal}"
  echo "                --clean, -c Clear out pub dependencies. Performs ```rm -rf .pub .packages pubspec.lock &&"
  echo "                 find . -name packages | xargs rm -rf```. Attempts to go into folders and"
  echo "                 clean them in there are any pubspec.yaml files."
  echo "                --clean-hard Performs all the actions of --clean in addition to clearing pub"
  echo "                 cache with ```rm -rf ~/.pub-cache```"
  echo "                --format, -f ```pub run dart_dev format``` of dart code."
  echo "                --get, -g Perform a ```pub get``` for pub dependencies. Will attempt to go"
  echo "                 into directories to find pubspec.yaml files."
  echo "                --help, -h Display this usage text."
  echo "                --serve, -s Serve dart code using ```pub run dart_dev serve```. Attempts to go into an"
  echo "                 app directory and serve from there if available."
  echo "                --test, -t Test dart code using ```pub run dart_dev test```."
  echo "                --upgrade, -u Perform ```pub upgrade``` in directories with a pubspec.yaml."
  echo
  echo "${underline}${bold}Example${normal}"
  echo "    ./qdart -gft"
  echo "    ./qdart --clean --get --serve"
  echo "    ./qdart -cgs"
  echo "    ./qdart -clean -gs"
}

options_found=0
while [ "$1" != "" ]; do
  options_found=1
  # Attempt to use GNU standard syntax
  case $1 in
    --clean-hard)
      q-clean-hard
      shift
      ;;
    --clean)
      q-clean
      shift
      ;;
    --format)
      q-format
      shift
      ;;
    --get)
      q-get
      shift
      ;;
    --help)
      usage
      shift
      ;;
    --serve)
      q-serve
      shift
      ;;
    --test)
      q-test
      shift
      ;;
    --upgrade)
      q-upgrade
      shift
      ;;
    *--*)
      # Bad GNU option
      echo "Invalid option: $1"
      usage
      exit 1
      ;;
    -*)
      # POSIX standard syntax
      while getopts :cfghstu- opt; do
        case $opt in
          c)
            q-clean
            ;;
          f)
            q-format
            ;;
          g)
            q-get
            ;;
          h)
            usage
            ;;
          s)
            q-serve
            ;;
          t)
            q-test
            ;;
          u)
            q-upgrade
            ;;
          -)
            # Invalid use of '-' or GNU standard
            # option used after POSIX option
            break
            ;;
          *)
            echo "Invalid POSIX Option: -$OPTARG" >&2
            usage
            exit 1
            ;;
        esac
      done
      shift
      ;;
    *)
      echo "Invalid option: $1"
      usage
      exit 1
      ;;
  esac
done

if ((!options_found)); then
  echo -e "No arguments found\n"
  usage
fi
